---
title: " Boye Kinzig Stream Parasites "
author: "Annemie Doliwa and Frédéric Mahé"
date: '`r format(Sys.time(), "%d %B %Y")`'

output:
  rmarkdown::html_document:
    theme: lumen
    toc: yes
    toc_float: TRUE
    keep_md: yes
    # code_folding: hide
---

```{r setup, include=FALSE}
rm(list = ls()) # remove all objects before starting
knitr::opts_chunk$set(echo = TRUE)
```


#### load required packages

```{r packages, message=FALSE}
library(here)
library(tidyverse)
library(readxl)
```

#### variables and functions

```{r}
input <- "full_table_Boye21_AD_OpenRefine05.10..xlsx"
output <- str_replace(input, "..xlsx", "_reduced_taxonomy.tsv")
annotated_table <- str_replace(output, ".tsv", ".xlsx")
```


## extract a list of unique taxa

That shorter list will then be annotated to identify parasitic taxa.

```{r}
here::here("data", input) %>%
    readxl::read_xlsx() %>%
        select(starts_with("Taxonomy")) %>%
        mutate(across(everything(), ~ str_remove(., " *\\([0-9]+\\)"))) %>%
        arrange(across(everything())) %>%
        distinct() %>%
        write_tsv(here::here("data", output))
```


## extract a list of parasitic taxa

Annemie and Micah have annotate the table.

```{r}
here::here("data", annotated_table) %>%
    readxl::read_xlsx(skip = 1) %>%
        select(ParasiticTax) %>%
        filter(! is.na(ParasiticTax)) %>%
        distinct() %>%
        pull() -> known_parasites

known_parasites
```

There are `r length(known_parasites)` taxa marked at parasites, at
different taxonomic levels.


***

```{r}
sessionInfo()
rm(list = ls())
```
